# Generated by Django 5.1.15 on 2026-04-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_business', '0002_add_is_test_eligible_rf15'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_test_eligible',
        ),
    ]
