# Generated by Django 6.0.2 on 2026-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo modificado')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Valor nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
            ],
            options={
                'verbose_name': 'Historial de cambio',
                'verbose_name_plural': 'Historial de cambios',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha de recarga')),
                ('channel', models.CharField(choices=[('ONLINE', 'En línea'), ('STORE', 'Tienda física'), ('ATM', 'Cajero automático'), ('APP', 'Aplicación móvil')], default='ONLINE', max_length=10, verbose_name='Canal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'ordering': ['-date'],
            },
        ),
    ]
